INSERT INTO SDS_GENERIC.SI_CONSUMER(CONSUMER_ID, CONSUMER_NM, CREATED_TS, CREATED_USR, MODIFIED_TS, MODIFIED_USR)
VALUES 
('PFIZER','Pfizer Inc.',SYSDATE,'Shanmugamp',SYSDATE,'Shanmugamp');
/
COMMIT;
/
INSERT INTO SDS_GENERIC.SI_CONSUMER_DELIVERY
(CONSUMER_ID, DELIVERY_FORMAT, DATE_FORMAT_FILE_POSTFIX, SEQ_FILE_NUM_FLAG, DATE_FORMAT_DATA, FREQUENCY_TYPE, FREQUENCY_WEEK_DAY, FREQUENCY_MONTH_DAY, CREATED_TS, CREATED_USR, MODIFIED_TS, MODIFIED_USR)
VALUES
('PFIZER','CSV','YYYYMMDD', 'N', 'MM/DD/YYYY', 'W', 6, NULL, SYSDATE, 'Shanmugamp',SYSDATE,'Shanmugamp');
/
 COMMIT;
 /
 Insert into SDS_GENERIC.SI_CONSUMER_FILE (CONSUMER_ID,DELIVERY_FORMAT,GENERIC_FILE_NM,CONSUMER_FILE_NM,DATABASE_VIEW_NM,WHERE_CLAUSE_TXT,CREATED_TS,CREATED_USR,MODIFIED_TS,MODIFIED_USR)
VALUES 
('PFIZER','CSV','ICON_CTMS_SITE_MIGRATION','ICON_site_issue','PFE_ICON_SITE_ISSUE',NULL,SYSDATE,'Shanmugamp',SYSDATE,'Shanmugamp');
/
commit;